### ISSUE TITLE
No data showing in OPC UA Client

### ISSUE THREAD

**Issue by codepoet80** [digitaltwinconsortium/ManufacturingDTDLOntologies#1]
I started the Debug configuration for Station (`station opc.tcp://station.munich.corp.contoso/ua/munich/ 200 6 yes`) and connected with an OPC UA client. I can see the server updating the time, so I know the connection is good, but the StationTelemetry values never update.
![StationDataNoUpdate](https://user-images.githubusercontent.com/16038880/151032659-bd6bd50d-75f5-417a-ab1e-f4d0d47845d2.png)

**Comment by barnstee** [comment]
You need to connect an MEs to make the machine move, or call execute manually, just like in real life! :-)

**Comment by codepoet80** [comment]
Working!
![StationWorking](https://user-images.githubusercontent.com/16038880/151202553-a4dbd8b8-03f2-4fb9-bf49-2a537562dbcb.png)
