### ISSUE TITLE
Azure Function vs Documentation

### ISSUE THREAD

**Issue by rploeg** [digitaltwinconsortium/ManufacturingDTDLOntologies#14]
In the Readme file for the documentation you mention to add the following environment variable to the config of the Azure Function App:

`UA_SERVER_DNS_NAME - set to "seattle"`

In the Azure Pressure Function the variable is stated as follows: 

`string uaServerLocationName = Environment.GetEnvironmentVariable("UA_SERVER_LOCATION_NAME");`

So documentation need to be changed to the right environment variable or the code in the variable.

**Comment by barnstee** [comment]
Fixed with https://github.com/digitaltwinconsortium/ManufacturingOntologies/commit/bfc9ea3bceef7c19bb3b1a40dc2d799423233ff4
