### ISSUE TITLE
USERNAME Function config is invalid

### ISSUE THREAD

**Issue by marktayl1** [digitaltwinconsortium/ManufacturingDTDLOntologies#15]
I am getting the following error when setting the ADXQuery function configuration:

> (Invalid or not allowed environment key name: USERNAME).

I changed it to ADX.USERNAME in config, ADXQuery.cs and local launch settings and that seemed to work.

**Comment by barnstee** [comment]
Ok, cool, will fix tomorrow...

**Comment by barnstee** [comment]
Fixed with https://github.com/digitaltwinconsortium/ManufacturingOntologies/commit/69d71c32142df9f7a3d4038c74ed849d2344dd7c
