### ISSUE TITLE
Anyone interested in a managed Grafana integration?

### ISSUE THREAD

**Issue by barnstee** [digitaltwinconsortium/ManufacturingDTDLOntologies#17]
Let me know by leaving a comment...

**Comment by rploeg** [comment]
Yes, need help?

**Comment by barnstee** [comment]
Always! :-) I forwarded you the internal thread on this, let's work on this together...

**Comment by rploeg** [comment]
See https://github.com/digitaltwinconsortium/ManufacturingOntologies/pull/20 for the first example Azure Managed Grafana dashboard. You can close this issue.

**Comment by barnstee** [comment]
Thank you @rploeg for the contribution! :-)
See here: https://github.com/digitaltwinconsortium/ManufacturingOntologies/blob/main/Tools/GrafanaDashboard/configuregrafana.md
