### ISSUE TITLE
Deployment AKS VM

### ISSUE THREAD

**Issue by rploeg** [digitaltwinconsortium/ManufacturingDTDLOntologies#18]
When deploying the solution I get an error message on the VM when I try to enable a new AKS:

![image](https://user-images.githubusercontent.com/49752333/233463531-75f6fa9a-f042-4f9f-851e-7c98b13c0d6f.png)

It looks like the OS needs too much memory so AKS cannot be deployed. Maybe deploy a D4s_v3 size of VM?

**Comment by barnstee** [comment]
Fixed with https://github.com/digitaltwinconsortium/ManufacturingOntologies/commit/1c1a3c68e452ef14baa49b14883e017f1e4e9918
