### ISSUE TITLE
Docker containers will not run on Windows Server 2019 in Azure

### ISSUE THREAD

**Issue by jwise-mfg** [digitaltwinconsortium/ManufacturingDTDLOntologies#2]
After solving all other problems, error is:
`docker: Error response from daemon: container d27e8606f2ea00c86299e54c0760f132fe864e09f2b8cba84a724efea0872b65 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2).`

To get this far you must:
- Install Docker (per [some dude](https://www.jorgebernhardt.com/how-to-install-docker-on-windows-servers/))
- Install runtimes (.NET core) and restore packages
- Change network configuration from `bridge` to `transparent` in BuildAndRunSimulation.bat
- Change container type to `mcr.microsoft.com/windows/servercore:ltsc2019` in Dockerfile (per [Docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/manage-windows-dockerfile))
- Change mount paths like: `-v c:\docker\shared:c:\shared -v c:\docker\logs:c:\logs` (or remove them entirely) (per [Docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/persistent-storage))
- Rip out all your hair

**Comment by barnstee** [comment]
I wouldn't bother with Windows Server in combination with windows Containers. I would stick with Windows Enterprise and Docker Desktop or a Linux distro with built-in Docker support. This is what I have tested and know is working.
