### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by HansHackmack** [digitaltwinconsortium/ManufacturingDTDLOntologies#35]
Hi,
i tried to deploy your project on my Azure for Students Account and ran into a few problems...

Am i right, that i have to create a virtual machine at first? Can you tell me, what specifications you used? Because i ran into limitations that i am not sure about, if they are because of an error or the limitations because of the student version.

Secondly and maybe because of my first Problems i get the error:
"ManufacturingOntologiesstorage" is not a valid storage account name. A storage account name must be between 3 and 24 characters long and may only contain numbers and lower case letters. (Code: AccountNameInvalid, target: ManufacturingOntologiesstorage)

I don't know if i can just change the name because of all the dependencies.

Best regards
Hans

**Comment by barnstee** [comment]
Hi Hans! Thanks for reaching out! ManufacturingOntologiesstorage has 30 characters, i.e. more than the limit of 24. Please chose a shorter name. Also, you don't need to create a separate VM, this is done for you as part of the deployment. It is possible that the student account has limitations in terms of what kind of virtual machines you can deploy, please try to deploy a Standard E2s v5 virtual machine as a test in your subscription to see if this is the problem.

**Comment by HansHackmack** [comment]
Hi Barnstee, thank you for your response.
I am new to Azure and i thought "ManufacturingOntologiesstorage" was part of your script and overlooked, that i was responsible for this mistake...
Yes, it seems like my student account is the reason for the problems while deploying. 
I manualy tried to deploy an instance of a E2s v5 machine (though it already said, that its not included or something...) and it failed.

thanks for your help anyway :)
