### ISSUE TITLE
AAS Repo not configured after deployment

### ISSUE THREAD

**Issue by AndreasFruehwirt** [digitaltwinconsortium/ManufacturingDTDLOntologies#36]
I am trying to figure out, how AAS Repository gets configured during provsioning as the repository remained empty after setup. Maybe you could point me into the right direction as I would like to figure out, how the data flows between all the parts of the reference implementation.

**Comment by barnstee** [comment]
You need to enable the AAS Repo to do its calculation, see: https://github.com/digitaltwinconsortium/ManufacturingOntologies?tab=readme-ov-file#enabling-the-product-carbon-footprint-calculation-pcf-in-the-asset-admin-shell-aas-repository

**Comment by AndreasFruehwirt** [comment]
Thanks for the input.
