### ISSUE TITLE
ADT

### ISSUE THREAD

**Issue by rploeg** [digitaltwinconsortium/ManufacturingDTDLOntologies#4]
Hi,

I see in the documentation that you leverage Azure Digital Twins. In the sample code I can 'only' find:
Simulator --> IoT Hub --> ADX. Is that correct? Is there no 'integration' sample with ADT? 

I have found the DTDL models that I can import in ADT, but don't see the flow yet between the other items.

thanks!

Remco

**Comment by barnstee** [comment]
There is a built-in extension in ADX to query ADT, see here for two sample queries:
https://github.com/digitaltwinconsortium/ManufacturingDTDLOntologies/blob/main/ADXQueries/GetStationsForLineMunich.kql
https://github.com/digitaltwinconsortium/ManufacturingDTDLOntologies/blob/main/ADXQueries/GetUACloudLibraryURLs.kql

so the flow goes: Simulator --> IoT Hub --> ADX <-- ADT

**Comment by rploeg** [comment]
Thanks, I saw that. But normally you 'store' the latest datapoints also in ADT (to create for example 3D maps). In this solution ADT is 'only' used as ontology if I am correct? 

Thanks for the great work!

**Comment by barnstee** [comment]
That's correct. For industrial workloads, you get much better perf sending data from IoT Hub directly to ADX and then querying the ADT graph via ADX, just like this reference implementation does.

**Comment by rploeg** [comment]
Thanks for explaining the choices!
